---
title: "SC_Project"
author: "Gordon Tang"
date: "7/2/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# We will be using the dplyr package for clean up and pre-processing 
library(dplyr)

# Then we read the data using the read.csv function.
data <- read.csv("SC_data.csv")
head(data)

#Only keep records where we know the birthdate.
data <- filter(data, !is.na(birthdateid))

#Only retain records where we know the gender
data$GenderCode<-as.character(data$GenderCode)
data <- filter(data, GenderCode!="")
data$GenderCode<-as.factor(data$GenderCode)

#Some odd age values... we'll replace with the median.
data$Age[data$Age < 0] <- median(data$Age)
data$Age[data$Age > 120] <- median(data$Age)

#If there are no reward numbers, we assign it a 0

data$UFlyRewardsNumber[is.na(data$UFlyRewardsNumber)] <- 0

#We construct a reward status factor variable.
data$UflyMemberStatus<-as.character(data$UflyMemberStatus)
data$UflyMemberStatus[data$UflyMemberStatus==''] <-"non-ufly"

#Discard duplicate records
data <- group_by(data, PNRLocatorID,CouponSeqNbr,PaxName,ServiceStartCity,ServiceEndCity,ServiceStartDate)
filter(data, n() == 1)

#Replace odd one off booking channels with 'Other'
data$BookingChannel<-as.character(data$BookingChannel)
data$BookingChannel[data$BookingChannel!="Outside Booking" 
										& data$BookingChannel!="SCA Website Booking" 
										& data$BookingChannel!="Tour Operator Portal" 
										& data$BookingChannel!="Reservations Booking" 
										& data$BookingChannel!="SY Vacation"] <- "Other"

data$BookingChannel<-as.factor(data$BookingChannel)

#Only keep records that involve SunCountry airlines tickets, for which MarketingAirlineCode=="SY".
data$MarketingAirlineCode<-as.character(data$MarketingAirlineCode)
data <- filter(data, MarketingAirlineCode == "SY")
data$MarketingAirlineCode<-as.factor(data$MarketingAirlineCode)

#Delete PNRs that have odd values and indicate an error.
data <- group_by(data, PNRLocatorID)
data <- mutate(data, error=ifelse(min(CouponSeqNbr)!=1,1,0))
filter(data, error==0)
head(data)

#Create a unique customer ID by concatenating name, gender and birthday
data <- mutate(data, UID = paste(EncryptedName, GenderCode, birthdateid,sep=""))

#Create Age buckets for age ranges, creating a new categorical variable "age_group" 
#with the following posisble values: "0-17", "18-24", "25-34", "35-54", "55+" and "N/A"
data <- mutate(data, age_group = ifelse(Age>=0 & Age<18, "0-17",
																 ifelse(Age>=18 & Age<25, "18-24",
																 ifelse(Age>=25 & Age<35, "25-34",
														 		 ifelse(Age>=35 & Age<55,"35-54",
									 			 				 ifelse(Age>=55,"55+", "NA"))))))

#For a given PNR, figure out true origin city (source of first leg)
true_origins <- data%>%
arrange(PNRLocatorID,CouponSeqNbr)%>% 
group_by(PNRLocatorID,PaxName)%>% 
do(data.frame(true_origin=first(.$ServiceStartCity)))

data<-merge(data,true_origins, by.x=c("PNRLocatorID","PaxName"),by.y = c("PNRLocatorID","PaxName"))

#For a given PNR, figure out final destination (target of last leg), 
final_destination <- data%>%
arrange(PNRLocatorID,CouponSeqNbr)%>% 
group_by(PNRLocatorID,PaxName)%>% 
do(data.frame(final_destination=last(.$ServiceEndCity)))

data<-merge(data, final_destination, by.x=c("PNRLocatorID","PaxName"),by.y = c("PNRLocatorID","PaxName"))

# We will use the lubridate package for operations involving date strings
install.packages("lubridate")
library(lubridate)

#Is the booking a round-trip or one-way?
data<-data%>%
mutate(round_trip = ifelse(as.character(true_origin)==as.character(final_destination), 1, 0))

# What is the size of the group?
data<-data%>%
group_by(PNRLocatorID)%>% 
mutate(group_size = length(unique(UID)))

# Create a binary indicator "group" corresponding to whether it was a group or single party traveling.
data<-data%>%
group_by(PNRLocatorID)%>% 
mutate(group= ifelse(group_size>1,1,0))

#Figure out which calendar quarter the trip took place in. 
# Create a categorical variable "Seasonality" which takes on the following values: 
# "Q1" for months 1:3, "Q2" for months 4:6, "Q3" for months 7:9 and "Q4" for months 10:12

data <- data %>%
mutate(Seasonality= ifelse(month(ServiceStartDate)>=1 & month(ServiceStartDate)<=3,  "Q1",
											ifelse(month(ServiceStartDate)>=4 & month(ServiceStartDate)<=6,  "Q2",
										  ifelse(month(ServiceStartDate)>=7 & month(ServiceStartDate)<=9,  "Q3",
											ifelse(month(ServiceStartDate)>=10 & month(ServiceStartDate)<=12,"Q4", 0)))))

#How many days in advance was the trip booked?
data$PNRCreateDate<-as.Date(data$PNRCreateDate) 
data$ServiceStartDate<-as.Date(data$ServiceStartDate) 
data<-data%>%
mutate(days_pre_booked=as.numeric(floor(difftime(ServiceStartDate,PNRCreateDate,units=c("days")))))

write.csv(data, "SC_data_CleanedUp.csv")

```
